# Generated by Django 4.1.4 on 2022-12-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_rating_user_alter_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='main.film'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raiting', to='main.user'),
        ),
    ]
